// server requests for server 3

###
//email send to user

GET http://localhost:4000/user/email

###
//get the user
GET http://localhost:4000/user/get:pavan

###
//get all users
GET http://localhost:4000/user/get

###

// register the user
POST http://localhost:4000/user/register-user
Content-Type: application/json

{
    "username":"AkshayKumar",
    "password":"AkshayKumar"
}
###
// login user
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "username":"AkshayKu",
    "password":"AkshayKu"
}
###

PUT http://localhost:3000/user/put
Content-Type: application/json

{
    "id":21,
    "name":"akshay",
    "age":40
}

###

// delete by id
DELETE http://localhost:11000/user/akash

//delete by name
###
DELETE http://localhost:11000/user/delete/akshay






<!--  >     ********************     other servers    **********************       <!-->

###
POST http://localhost:9000/user/post
Content-Type: application/json

{
    "id":14,
    "name":"akshay",
    "age":30
}
###

###

GET http://localhost:3500/get/12

###

###


//        products

###

GET http://localhost:3500/get-products

###

GET http://localhost:3500/get-product/11

###

POST http://localhost:3500/create-products
Content-Type: application/json

{
    "id":11,
    "name":"choco",
    "brand":"cadburry"
}
###
PUT http://localhost:3500/update-products
Content-Type: application/json

{
    "id":11,
    "name":"akash",
    "brand":"nestle"
}

###

DELETE http://localhost:3500/delete-products/11


